### ISSUE TITLE
 Unexpected output when negotiating contents to be returned from the INSPIRE Media Subtype code list

### ISSUE THREAD

**Issue by jescriu** [INSPIRE-MIF/helpdesk-registry#40] opened 2022-10-21 08:58 UTC
Dear INSPIRE Registry technical maintenance team,

I want to draw your attention to the following issue detected yesterday in the scope of the INSPIRE Reference Validator helpdesk: 
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/860

As you can see in the description of the issue, one of the tests of the validator is failing due to an unexpected output from a request to the INSPIRE Registry (http://inspire.ec.europa.eu/media-types/application), which seems to be returning an .html output instead of an .xml one, although the 'Accept'-Header is set to 'application/atom+xml'.

Therefore, there seems to be an issue in the content negotiation process. Note that the affectation is possibly affecting all code list, not only the INSPIRE Media Subtype one. 

Please **assign maximum priority to solve this issue** - Start analysing it as soon as possible to speed up its resolution in both, the INSPIRE Registry and the Re3gistry software (where needed).  

- Description of the steps to reproduce the issue: See https://github.com/INSPIRE-MIF/helpdesk-validator/issues/860
- the browser and version used: N/A
- a screenshot illustrating the problem: N/A
- the URI of the reference code or the URL of the page: http://inspire.ec.europa.eu/media-types/application

Thank you.

**Comment by mwjsanders** [comment] 2022-11-01 11:05
This seems a critical error in the inspire registry. Please provide a fix for this issue

**Comment by oscar9** [comment] 2022-11-16 09:10
Dear everyone,

We have analyzed the error and found a solution for it. We are in the process of testing the solution and if everything works correctly, it will be updated on the production server. Thanks for waiting.

Best regards,
Óscar

**Comment by arantzaetxebarria** [comment] 2022-12-02 11:09
Dear everyone,

A solution has been implemented in the INSPIRE Registry production environment. Now the returned response from http://inspire.ec.europa.eu/media-types/application contains XML data because the Accept header is set to application/atom+xml.

INSPIRE Registry technical maintenance team, will continue to work on testing that all formats, apart from ATOM, work correctly.

Regards,
Arantza

**Comment by mwjsanders** [comment] 2022-12-09 15:17
@arantzaetxebarria,

as reported in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/860 the problem is back

**Comment by arantzaetxebarria** [comment] 2022-12-15 06:49
Dear @mwjsanders 

Could you confirm as it is indicated in issue [860 ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/860) that now is working correctly? Thanks

Regards

**Comment by mwjsanders** [comment] 2022-12-15 07:19
@arantzaetxebarria 

everything is working correctly now, this issue can be closed

Regards Mark

**Closed** 2022-12-15 07:20 UTC
Labels: solved

**Comment by arantzaetxebarria** [comment] 2022-12-15 10:48
As the solution to this issue is closely related to the Re3gistry Software, it has been decided to create a new [issue](https://github.com/ec-jrc/re3gistry/issues/241) in its repository and add it for the next release. 

Regards
