### ISSUE TITLE
Error message on frontend

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-registry#94] opened 2024-04-04 07:36 UTC
Dear INSPIRE team,

seems [INSPIRE registry frontend](https://inspire.ec.europa.eu/registry) is down. Any indication, when the service will be back again?

Thanks, Martin

![obrázok](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/6195936/93d570ce-1129-4a9a-94a7-936c25298bbf)

**Comment by jescriu** [comment] 2024-04-04 07:43
Dear @MartinTuchyna,
Thanks you for contacting us.
I cannot reproduce the error: https://inspire.ec.europa.eu/registry is working fine for me.
The system is caching the whole content of the registry since Monday morning, and it did not finished yet. This may cause potential issues from time to time. 
Please let us know if the issue persists.

**Comment by MartinTuchyna** [comment] 2024-04-04 08:51
Dear @jescriu 

Thanks it seems to be OK, now.

**Comment by jescriu** [comment] 2024-04-04 08:56
Good to know @MartinTuchyna.
I proceed to close this issue. Feel free to re-open it if the problem happens again.

**Closed by jescriu** 2024-04-04 08:56 UTC
